KAS-2492 handtekeningen verwijderen
kanselarij-vlaanderen/kaleidos-project pull request #219
Opened 2021-08-18 12:45 UTC by TaneeG

Build : http://kal-kastaar.s.redpencil.io:8080/job/kaleidos/job/custom_frontend_backend_combination/94/
PR: kanselarij-vlaanderen/kaleidos-frontend#1044

2021-08-20 08:36 UTC, MikiDi commented on config/migrations/20210817155000-delete-signatures.sparql
> +PREFIX  ext:  <http://mu.semte.ch/vocabularies/ext/>
Steek je deze eens in http://www.sparql.org/validate/update @TaneeG ?

2021-08-20 10:53 UTC, ValenberghsSven requested changes
er zit nog iets in de mu-auth config
`"http://mu.semte.ch/vocabularies/ext/Handtekening", # TODO: check if this type is in use.`

2021-08-20 10:53 UTC, ValenberghsSven commented on config/migrations/20210817155000-delete-signatures.sparql
> +DELETE WHERE{ ext:Handtekening  ext:bevoegdePersoon  person:Person };
Query werkt idd niet, check dat even met een validator
ik gebruik zelf ook soms https://yasgui.triply.cc/

Daarnaast, als deze 2 deletes zouden werken, deze doen niks.
Dit zijn allebei onderdeel van de eerder verwijderde ?s ?p ?o .
+ je hebt alle `ext:Handtekening` types al verwijdert dus zelfs als er data zou zijn vindt je die op deze manier niet meer

Daarnaast heb je nog de inverse relatie `ext:heeftHandtekening`, maar we kunnen eerst checken of er wel data van bestaat op ACC/PROD, om te checken om de migratie nodig is

2021-08-23 19:15 UTC, MikiDi commented on config/migrations/20210817155000-delete-signatures.sparql
> +PREFIX  ext:  <http://mu.semte.ch/vocabularies/ext/>
Kan je dat nog eens doen? :-/

2021-08-24 14:42 UTC, merged