Feature/kas 3170 decreten naar themis
kanselarij-vlaanderen/kaleidos-project pull request #254
Opened 2022-03-02 12:38 UTC by TaneeG

Jira: https://kanselarij.atlassian.net/browse/KAS-3170

2022-03-02 18:32 UTC, erikap requested changes
`ext:zittingDocumentversie` is niet het path waarmee decreten aan een zitting gekoppeld zijn (@MikiDi correct me if I'm wrong). Je kan het gebruikte path afleiden uit de [export voor Themis](https://github.com/kanselarij-vlaanderen/themis-export-service/blob/487db3a89f021442394c46ca24c2800db8e7479e/support/sparql-queries.js#L440-L446).

Ik denk dat je best op basis van een dump van production data met een SPARQL query een unieke lijst van meetings samenstelt. En dan een migration opstelt op basis van die lijst van meetings.

Die migration moet trouwens niet toegevoegd worden aan de git repos (zie accept criteria van jira story).

2022-03-02 18:34 UTC, erikap commented on config/future_migrations/20220301140000-decreten-naar-themis/20220301140000-create-themis-activity-for-each-doc.sparql
> +      BIND(IRI(STR(?meeting)) AS ?newUri
Een andere URI dan de meeting URI gebruiken voor de `ext:ThemisPublicationActivity` die geinsert wordt

2022-03-03 07:49 UTC, TaneeG commented
Ik heb het op deze git gezet voor gemakkelijk te reviewen enzo. Dermee in de map future migrations. Erna mag deze weg

2022-03-03 12:42 UTC, TaneeG commented
@erikap @MikiDi Er is nu een aparte select voor de zittingen en ene waar erna de  uitgekomen zittingen in moeten bij de values

2022-03-14 08:57 UTC, erikap commented
Ik ga deze afsluiten aangezien er, zoals @MikiDi in #242  al aangaf, een nieuwe iteratie komt van de originele story. Deze vervolgstory moet dus niet uitgevoerd worden atm.

2022-03-14 08:57 UTC, closed without merging