Feature/kas 2430 gebruik vergaderactiviteit codelist uit backend om keuzelijst op te stellen in frontend
kanselarij-vlaanderen/kaleidos-project pull request #262
Opened 2022-03-28 14:45 UTC by sergiofenoll

Draft, waiting for Jenkins tests to pass

2022-03-30 14:04 UTC, ValenberghsSven requested changes

2022-03-30 14:04 UTC, ValenberghsSven commented on config/dispatcher/dispatcher.ex
> +  end
`get` ipv `match`. Dan komen er zeker geen wijzigingen vanuit de frontend. Doen we ook voor sommige andere code lists.

2022-03-30 14:04 UTC, ValenberghsSven commented on config/migrations/20220328134352-minister-council-types-ordering.ttl
> +kind:A5D6B7A8-2F9C-44B6-B3BE-98D80B426254 ext:priority 1 . # Ministerraad
`schema:position` ipv `ext:priority`? Dat is een change dat we ook op andere resources gedaan hebben/ gaan doen

2022-03-30 14:04 UTC, ValenberghsSven commented on config/migrations/20220328134352-minister-council-types-ordering.ttl
> +    skos:altLabel "Ministerraad via elektronische procedure" .
`"Ministerraad via elektronische procedure"@nl .`? we doen dat niet consistent, niet zeker wat de meerwaarde is als we enkel `@nl` waardes hebben.

2022-03-30 14:04 UTC, ValenberghsSven commented on config/resources/besluit-domain.lisp
> +  :on-path "meeting-kinds")
Moet er voor deze concept resource ook een `a <http://www.w3.org/2004/02/skos/core#ConceptScheme>` worden toegevoegd?

2022-03-30 14:04 UTC, ValenberghsSven commented on config/authorization/config.ex
> +      "http://mu.semte.ch/vocabularies/ext/MinisterraadType",
Dit valt onder de `unconfidential_resource_types`

2022-03-30 14:04 UTC, ValenberghsSven commented on config/authorization/config.ex
> +      "http://mu.semte.ch/vocabularies/ext/MinisterraadType",
Momenteel werkt het gewoon omdat de data in de public graph staat door migraties.
De resource enkel hier vermelden zou betekenen dat edits op dit model of nieuwe types maken (als we dit zouden toelaten in frontend) enkel worden gepersisteerd op de kanselarij graph.

2022-03-30 21:29 UTC, sergiofenoll commented on config/resources/besluit-domain.lisp
> +  :on-path "meeting-kinds")
Ik denk dat dat deel zal zijn van [deze ticket](https://kanselarij.atlassian.net/browse/KAS-2429), want die Themis resources zijn inderdaad `skos:Concept` (maar de `ext:MinisterraadType` resources die we nu gebruiken zijn geen `skos:Concept`s)

2022-03-30 21:29 UTC, sergiofenoll commented on config/authorization/config.ex
> +      "http://mu.semte.ch/vocabularies/ext/MinisterraadType",
Thanks! was niet helemaal mee met hoe de auth groepen in elkaar zitten

2022-03-31 09:56 UTC, ValenberghsSven commented on config/resources/besluit-domain.lisp
> +  :on-path "meeting-kinds")
ah idd, dan moeten we dat niet doen op deze als we die ooit gaan weggooien

2022-03-31 13:50 UTC, erikap requested changes
Ik zou geen nieuwe resource definiëren, maar de bestaande `concept`-resource uit `concept-domain.json` gebruiken waarbij `broader` en `narrower` als relaties gedefinieerd zijn. Dit gaat de transitie naar de concepten vanop Themis in de follow-up story vergemakkelijken. Aan die `concept` resource mag wel `schema:position` toegevoegd worden. 

In de backend moet er dan enkel een migration toegevoegd worden om de bestaande ministerraad-types ook class `skos:Concept` te geven en ze toe te voegen aan het concept scheme `<http://themis.vlaanderen.be/id/concept-scheme/8030c0c4-aff1-4548-92d9-3299ebc43832>` via `skos:inScheme`.

De lijst van opties voor de frontend zijn dan alle concepts zonder `narrower`, gefilterd op het concept-scheme van ministerraad-types zoals bvb. [ook al voor beleidsdomeinen gebeurd](https://github.com/kanselarij-vlaanderen/frontend-kaleidos/blob/development/app/components/utils/government-areas/edit-government-areas-modal.js#L24-L28).

2022-03-31 13:53 UTC, erikap commented on config/resources/besluit-domain.lisp
> +  :on-path "meeting-kinds")
Zie ook mijn andere comment. Ik zou de transitie naar `skos:Concept` wel al in deze PR doen, zodanig dat de followup-story KAS-2429 zich louter beperkt tot het updaten van URIs in de data, maar er dan geen implementatie in frontend meer moet wijzigen.

2022-03-31 14:35 UTC, sergiofenoll commented
@erikap wat met de postfix? Mag dat toegevoegd worden aan de `concept` resource? Of eerder de bestaande property `skos:scopeNote` ervoor gebruiken (denk niet dat dat daar 100% past, maar mss beter dan een super specifieke property toe te voegen)?

2022-03-31 14:43 UTC, ValenberghsSven commented
> @erikap wat met de postfix? Mag dat toegevoegd worden aan de `concept` resource? Of eerder de bestaande property `skos:scopeNote` ervoor gebruiken (denk niet dat dat daar 100% past, maar mss beter dan een super specifieke property toe te voegen)?

Ik ben eerder niet opgekomen, maar die postfix is precies enkel nodig in frontend.
Mogelijk is het wel doe moeite om dat uit het model te halen zodat we concepten kunne gebruiken?

2022-03-31 15:05 UTC, erikap commented
> > @erikap wat met de postfix? Mag dat toegevoegd worden aan de `concept` resource? Of eerder de bestaande property `skos:scopeNote` ervoor gebruiken (denk niet dat dat daar 100% past, maar mss beter dan een super specifieke property toe te voegen)?
> 
> Ik ben eerder niet opgekomen, maar die postfix is precies enkel nodig in frontend. Mogelijk is het wel de moeite om dat uit het model te halen zodat we concepten kunnen gebruiken zonder extra properties?

`skos:notation` zou dan nog het meest geschikte zijn. Maar als die enkel in frontend gebruikt wordt (nice catch @ValenberghsSven) om de meeting identifier string samen te stellen, kan die inderdaad enkel daar gespecifieerd worden.

2022-03-31 16:42 UTC, sergiofenoll commented
> In de backend moet er dan enkel een migration toegevoegd worden om de bestaande ministerraad-types ook class skos:Concept te geven en ze toe te voegen aan het concept scheme <http://themis.vlaanderen.be/id/concept-scheme/8030c0c4-aff1-4548-92d9-3299ebc43832> via skos:inScheme.

Probleem hiermee: the Themis vergaderactiviteittypes zitten al in de DB, en zijn ook gelinkt aan datzelfde `skos:ConceptScheme` (waardoor we van de backend een lijst krijgen waarin elk type 2 keer in voorkomt).

Goed als ik voor deze ticket dan een extra scheme maak?

2022-03-31 16:45 UTC, erikap commented
> > In de backend moet er dan enkel een migration toegevoegd worden om de bestaande ministerraad-types ook class skos:Concept te geven en ze toe te voegen aan het concept scheme http://themis.vlaanderen.be/id/concept-scheme/8030c0c4-aff1-4548-92d9-3299ebc43832 via skos:inScheme.
> 
> Probleem hiermee: the Themis vergaderactiviteittypes zitten al in de DB, en zijn ook gelinkt aan datzelfde `skos:ConceptScheme` (waardoor we van de backend een lijst krijgen waarin elk type 2 keer in voorkomt).
> 
> Goed als ik voor deze ticket dan een extra scheme maak?

Ja, dat is goed. Ik wist niet dat de nieuwe URIs al in de Kaleidos DB zaten.

2022-03-31 23:45 UTC, erikap requested changes
Changes in authorization config en dispatcher moeten nog gerevert worden.

2022-04-01 08:36 UTC, erikap approved these changes

2022-04-01 15:49 UTC, ValenberghsSven approved these changes

2022-04-01 15:55 UTC, merged