KAS-3295 Refactor agendaitem properties
kanselarij-vlaanderen/kaleidos-project pull request #267
Opened 2022-04-07 14:35 UTC by sergiofenoll

Frontend PR: https://github.com/kanselarij-vlaanderen/frontend-kaleidos/pull/1286
themis-export-service PR: https://github.com/kanselarij-vlaanderen/themis-export-service/pull/1
agenda-approve-service PR: https://github.com/kanselarij-vlaanderen/agenda-approve-service/pull/23
newsletter-service PR: https://github.com/kanselarij-vlaanderen/newsletter-service/pull/43

- dct:alternative -> besluitvorming:korteTitel
- besluitvorming:aanmaakdatum -> dct:created
- ext:modified -> dct:modified
- ext:toelichting -> schema:comment
- :explanation -> :comment
- ext:priority -> schema:position
- remove besluitvorming:notulen

Also adds migration for the changed predicates

Used following command to look for all predicates (using ripgrep) across all services defined either app-kaleidos, app-themis, app-overlegcomite, app-persberichten:
`rg -nwe '((http://purl.org/dc/terms/|dct:)alternative|(http://data.vlaanderen.be/ns/besluitvorming#|besluitvorming:)(aanmaakdatum|notulen)|(http://mu.semte.ch/vocabularies/ext/|ext:)(modified|toelichting|priority))' */`

Only instances of said predicates that remain are in migrations and other resources than agendaitem:
```
themis-export-service/support/sparql-queries.js:401:    optionalStatements.push(`<${newsitem.uri}> dct:alternative ${sparqlEscapeString(newsitem.alternative)} .`);
kaleidos-project/config/resources/publicatie-domain.json:28:          "predicate": "dct:alternative"
kaleidos-project/config/resources/publicatie-domain.json:144:          "predicate": "dct:alternative"
kaleidos-project/config/resources/publicatie-domain.json:215:          "predicate": "dct:alternative"
kaleidos-project/config/resources/publicatie-domain.json:585:          "predicate": "ext:priority"
kaleidos-project/config/resources/dossier-domain.lisp:4:                (:short-title   :string   ,(s-prefix "dct:alternative"))
kaleidos-project/config/resources/dossier-domain.lisp:37:  :properties `((:short-title         :string ,(s-prefix "dct:alternative"))
kaleidos-project/config/resources/dossier-domain.lisp:43:                (:modified            :datetime ,(s-prefix "ext:modified"))
kaleidos-project/config/search/config.json:201:        "shortTitle": "http://purl.org/dc/terms/alternative",
kaleidos-project/config/search/config.json:235:          "http://purl.org/dc/terms/alternative"
kaleidos-project/config/search/config.json:323:        "shortTitle": "http://purl.org/dc/terms/alternative",
kaleidos-project/config/resources/handtekening-domain.json:24:          "predicate": "dct:alternative"
kaleidos-project/config/migrations/20201124111200-add-publication-type.sparql:12:      ext:priority 2 ;
kaleidos-project/config/migrations/20201224101445-publication-flow-ingetrokken.sparql:11:      ext:priority 3 ;
kaleidos-project/config/migrations/20201224101445-publication-flow-ingetrokken.sparql:17:      ext:priority 4 ;
kaleidos-project/config/migrations/20201020150000-publication-status.sparql:16:      ext:priority 1 ;
kaleidos-project/config/migrations/20201020150000-publication-status.sparql:22:      ext:priority 2 ;
kaleidos-project/config/migrations/20201020150000-publication-status.sparql:29:      ext:priority 1 ;
kaleidos-project/config/migrations/20201020150000-publication-status.sparql:35:      ext:priority 2 ;
kaleidos-project/config/migrations/20201020150000-publication-status.sparql:41:      ext:priority 3 ;
kaleidos-project/config/migrations/20201020150000-publication-status.sparql:63:      ext:priority 1 ;
kaleidos-project/config/migrations/20200616142826-decision-result-code.sparql:10:            ext:priority 1;
kaleidos-project/config/migrations/20200616142826-decision-result-code.sparql:16:            ext:priority 2;
kaleidos-project/config/migrations/20200616142826-decision-result-code.sparql:22:            ext:priority 3;
kaleidos-project/config/migrations/20200616142826-decision-result-code.sparql:28:            ext:priority 3;
kaleidos-project/config/resources/besluit-domain.lisp:136:                (:priority    :integer ,(s-prefix "ext:priority"))
kaleidos-project/config/migrations/20210413110000-publicationflow-publication-status.sparql:48:        ?s ext:priority ?prio.
kaleidos-project/config/migrations/20210413110000-publicationflow-publication-status.sparql:59:            ext:priority ?prio.
kaleidos-project/config/migrations/20200629150006-add-startdate-to-activities.sparql:14:        ?agendaitems besluitvorming:aanmaakdatum ?datum.
kaleidos-project/config/migrations/20191030164610-insert-newsletter-info-for-subcase-without-newsletter-info.sparql:12:              dct:alternative ?subcaseShortTitle ;
kaleidos-project/config/migrations/20191030164610-insert-newsletter-info-for-subcase-without-newsletter-info.sparql:28:            ?sub dct:alternative ?subcaseShortTitle.
kaleidos-project/config/migrations/20220407152557-fix-agendaitem-predicates.sparql:8:        ?agendapunt dct:alternative ?shortTitle ;
kaleidos-project/config/migrations/20220407152557-fix-agendaitem-predicates.sparql:9:            besluitvorming:aanmaakdatum ?created ;
kaleidos-project/config/migrations/20220407152557-fix-agendaitem-predicates.sparql:10:            ext:modified ?modified ;
kaleidos-project/config/migrations/20220407152557-fix-agendaitem-predicates.sparql:11:            ext:toelichting ?comment ;
kaleidos-project/config/migrations/20220407152557-fix-agendaitem-predicates.sparql:12:            ext:priority ?position .
kaleidos-project/config/migrations/20220407152557-fix-agendaitem-predicates.sparql:28:        OPTIONAL { ?agendapunt dct:alternative ?shortTitle . }
kaleidos-project/config/migrations/20220407152557-fix-agendaitem-predicates.sparql:29:        OPTIONAL { ?agendapunt besluitvorming:aanmaakdatum ?created . }
kaleidos-project/config/migrations/20220407152557-fix-agendaitem-predicates.sparql:30:        OPTIONAL { ?agendapunt ext:modified ?modified . }
kaleidos-project/config/migrations/20220407152557-fix-agendaitem-predicates.sparql:31:        OPTIONAL { ?agendapunt ext:toelichting ?comment . }
kaleidos-project/config/migrations/20220407152557-fix-agendaitem-predicates.sparql:32:        OPTIONAL { ?agendapunt ext:priority ?position . }
```

2022-04-08 12:55 UTC, ValenberghsSven requested changes

2022-04-08 12:55 UTC, ValenberghsSven commented on config/migrations/20220407152557-fix-agendaitem-predicates.sparql
> +        ?agendapunt a besluitvorming:Agendapunt .
`Agendapunt` is `besluit:Agendapunt`, not `besluitvorming:Agendapunt`
The rest looks good.

2022-04-08 13:48 UTC, ValenberghsSven commented on config/migrations/20220407152557-fix-agendaitem-predicates.sparql
> +            ext:priority ?position .
`ext:prioriteit` and in where statement

2022-04-08 14:04 UTC, ValenberghsSven approved these changes

2022-04-12 16:04 UTC, erikap approved these changes

2022-04-12 16:04 UTC, erikap commented
All impacted backend services have been released and bumped. Awaiting a successful Jenkins run of https://github.com/kanselarij-vlaanderen/frontend-kaleidos/pull/1286 before merging.

2022-04-12 21:04 UTC, merged