KAS-3608: Blocking users, memberships, and organizations
kanselarij-vlaanderen/kaleidos-project pull request #324
Opened 2022-10-13 14:22 UTC by sergiofenoll

2022-10-14 11:37 UTC, erikap requested changes
Migration toevoegen om active status te zetten voor mock gebruikers/organisaties/memberships.

Kan waarschijnlijk met een generieke SPARQL query op basis van `?account foaf:accountServiceHomepage <https://github.com/kanselarij-vlaanderen/mock-login-service>`

2022-10-14 11:37 UTC, erikap commented on config/migrations/20221013105306-blocked-mock-users.ttl
> +@prefix mu: <http://mu.semte.ch/vocabularies/core/> .
Deze test-data zou ik vermijden om in de git repos te steken, want die gaat ook op productie terecht komen.

2022-10-14 16:04 UTC, sergiofenoll commented on config/migrations/20221013105306-blocked-mock-users.ttl
> +@prefix mu: <http://mu.semte.ch/vocabularies/core/> .
Hoe doen we dat dan met de "echte" mock users die gebruikt worden op dev? Staan die niet ook in een migratie? Ik ging ervan uit dat er een mechanisme was om bepaalde migraties te skippen op ACC/PROD. Is het gewoon de bedoeling om die triples in de DB te zetten en dan de zip te updaten?

2022-10-17 10:38 UTC, erikap approved these changes

2022-10-19 14:35 UTC, merged