Feature/kas 3875 besluitvorming http prefix to https
kanselarij-vlaanderen/kaleidos-project pull request #370
Opened 2023-02-23 16:01 UTC by StuyckRuben

https://kanselarij.atlassian.net/browse/KAS-3875

- [x] merged https://github.com/kanselarij-vlaanderen/agenda-approve-service/pull/36
- [x] merged https://github.com/kanselarij-vlaanderen/cache-warmup-service/pull/10
- [x] merged https://github.com/kanselarij-vlaanderen/agenda-comparison-service/pull/11
- [x] merged https://github.com/kanselarij-vlaanderen/newsletter-service/pull/51
- [x] merged https://github.com/kanselarij-vlaanderen/yggdrasil/pull/53
- [x] merged https://github.com/kanselarij-vlaanderen/file-bundling-job-creation-service/pull/4
- [x] merged https://github.com/kanselarij-vlaanderen/case-documents-sync-service/pull/4
- [x] merged https://github.com/kanselarij-vlaanderen/gov-field-sync-service/pull/4
- [x] merged https://github.com/kanselarij-vlaanderen/publication-report-service/pull/10
- [x] merged https://github.com/kanselarij-vlaanderen/document-versions-service/pull/2
- [x] shortlist-service updated (service not merged into app-kaleidos yet)

2023-02-24 08:20 UTC, ValenberghsSven commented
Add all other service PR's in here, they all have to go at once.
This PR will need to be communicated properly. when it happens, everyone needs to update their stack and make sure that there is no more use of the `http` version in their code that they are working on..

2023-02-24 08:25 UTC, tdn commented
I'd be inclined to make this a separate release once we're ready for it

2023-03-06 13:15 UTC, ValenberghsSven commented
When we release, rename all the migration files to a recent date to reflect the correct order to run the migrations.
If not, these migrations might be listed before others that were created at a later date but already run on ACC/PROD

2023-04-18 11:58 UTC, ValenberghsSven commented
add: shortlist service.
Other services?

2023-04-18 15:57 UTC, ValenberghsSven requested changes
Er zijn wat overbodige migraties

2023-04-18 15:57 UTC, ValenberghsSven commented on config/migrations/20230223102500-change-http-to-https-besluitvorming-isgeagendeerdvia.sparql
Deze relatie zou niet meer mogen bestaan, verwijderd in 2020

2023-04-18 15:57 UTC, ValenberghsSven commented on config/migrations/20230223112000-change-http-to-https-besluitvorming-verdaagd.sparql
Deze relatie zou niet meer mogen bestaan. Niet zeker vanwaar dit komt.
Er is enkel ooit een type `besluitvorming:Verdaagd` geweest, maar is verwijderd 2020

2023-04-18 15:57 UTC, ValenberghsSven commented on config/migrations/20230223120500-change-http-to-https-besluitvorming-verdaagd.sparql
duplicate? `besluitvorming:verdaagd` zou niet mogen bestaan + er zijn 2 migratie files hiervoor

2023-04-18 15:57 UTC, ValenberghsSven commented on config/migrations/20230223104000-change-http-to-https-besluitvorming-gearchiveerd.sparql
bestaat niet?

2023-04-18 15:57 UTC, ValenberghsSven commented on config/migrations/20230223103500-change-http-to-https-besluitvorming-isaangevraagdvoor.sparql
relatie is al verwijderd 11/2022

2023-04-18 17:11 UTC, ValenberghsSven commented on config/migrations/20230223112000-change-http-to-https-besluitvorming-verdaagd.sparql
wat is dit? net gezocht op ACC.
Er zijn 18 hits hierop maar dit is bvb.
`<http://kanselarij.vo.data.gift/id/verdaagden/5DD7AAB85084E70008000043>  besluitvorming:verdaagd "false"`

Voor de rest hangt daar totaal niets aan.
![image](https://user-images.githubusercontent.com/22245223/232853217-5c30fa81-dd57-4f91-bcc9-eac51b497e90.png)

2023-04-18 17:12 UTC, ValenberghsSven commented on config/migrations/20230223112000-change-http-to-https-besluitvorming-verdaagd.sparql
geen metadata, geen type.
Ik vermoed een restant van `besluitvorming:Verdaagd` type dat ooit gebruikt was voor uitgestelde agendapunten?
Triples mogen volgens mij gewoon weg

2023-04-18 17:13 UTC, ValenberghsSven commented on config/migrations/20230223102500-change-http-to-https-besluitvorming-isgeagendeerdvia.sparql
0 op ACC

2023-04-18 17:19 UTC, ValenberghsSven commented on config/migrations/20230223104000-change-http-to-https-besluitvorming-gearchiveerd.sparql
op ACC wel een deel hits van 2019 op documenten.
Die documenten zijn van het type `foaf:Document`.
Dat gebruiken we niet? in migraties terug te vinden, maar niet zeker waarvoor dit dient.....
![image](https://user-images.githubusercontent.com/22245223/232854638-f9c4b706-1054-427e-9e78-e2941097a7ca.png)

2023-04-18 17:19 UTC, ValenberghsSven commented on config/migrations/20230223103500-change-http-to-https-besluitvorming-isaangevraagdvoor.sparql
0 op ACC

2023-04-18 17:26 UTC, ValenberghsSven commented on config/migrations/20230223104000-change-http-to-https-besluitvorming-gearchiveerd.sparql
Ik zou moeten graven in oude code om te weten wat dit is
We kunnen all eens kijken of deze docs vandaag zichtbaar zijn.
[besluitvorming-gearchiveerd.ods](https://github.com/kanselarij-vlaanderen/app-kaleidos/files/11264623/besluitvorming-gearchiveerd.ods)

2023-04-18 17:27 UTC, ValenberghsSven commented on config/migrations/20230223104000-change-http-to-https-besluitvorming-gearchiveerd.sparql
worst case gewoon de migratie laten uitvoeren en achteraf weggooien

2023-04-18 17:34 UTC, ValenberghsSven commented on config/migrations/20230223102500-change-http-to-https-besluitvorming-isgeagendeerdvia.sparql
verwijderd

2023-04-18 17:35 UTC, ValenberghsSven commented on config/migrations/20230223120500-change-http-to-https-besluitvorming-verdaagd.sparql
verwijderd

2023-04-18 17:35 UTC, ValenberghsSven commented on config/migrations/20230223103500-change-http-to-https-besluitvorming-isaangevraagdvoor.sparql
verwijderd

2023-04-18 17:38 UTC, ValenberghsSven commented
> add: shortlist service. Other services?
Themis-export-service heeft een workaround momenteel om die triples te corrigeren, dat moet er dan eens uit

2023-04-19 11:55 UTC, ValenberghsSven commented on config/migrations/20230223102500-change-http-to-https-besluitvorming-isgeagendeerdvia.sparql
hmm raar, gisteren had ik geen hits, maar bij controle blijkt er toch 1 resultaat te zijn op elke graph
![image](https://user-images.githubusercontent.com/22245223/233067297-ca6bdb00-b18c-43ab-8b65-31c28c690c11.png)

2023-04-19 11:56 UTC, ValenberghsSven commented on config/migrations/20230223102500-change-http-to-https-besluitvorming-isgeagendeerdvia.sparql
Zal de migratie terugzetten, maar dit zou niet mogen bestaan. Controleren of alles goed zit qua data daar....

2023-04-19 12:05 UTC, ValenberghsSven commented on config/migrations/20230223103500-change-http-to-https-besluitvorming-isaangevraagdvoor.sparql
gelijkaardig aan vorige comment. Ik krijg vandaag wel hits. Niet zekr wat ik gisteren heb fout gedaan.
Maar deze relatie zou niet mogen bestaan (ooit aangepast naar `ext:isAangevraagdVoor` en daarna in het geheel verwijderd.
Deze relatie zou dus uiteindelijk weg moeten (en onderzoeken waarom deze nog bestaat na migratie `20200908131700-replace-besluitvorming-isAangevraagdVoor-with-ext-isAangevraagdVoor-.sparql`

2023-04-19 12:05 UTC, ValenberghsSven commented on config/migrations/20230223103500-change-http-to-https-besluitvorming-isaangevraagdvoor.sparql
zet deze terug zodat deze aangepast wordt

2023-04-19 12:47 UTC, ValenberghsSven approved these changes
I think it's all covered.
Made a PR for themis-export-service that needs to be merged after our app is updated so the next export is working

2023-04-19 12:49 UTC, merged

2023-04-24 09:27 UTC, tdn commented on config/migrations/20230223112000-change-http-to-https-besluitvorming-verdaagd.sparql
https://kanselarij.atlassian.net/browse/KAS-4056

2023-04-25 09:30 UTC, tdn commented on config/migrations/20230223104000-change-http-to-https-besluitvorming-gearchiveerd.sparql
Wordt idd niet meer gebruikt in resources. Misschien oude manier om documenten te verwijderen?
Toegevoegd aan https://kanselarij.atlassian.net/browse/KAS-4056 om te verwijderen.