KAS-3797: Slow government domain requests
kanselarij-vlaanderen/kaleidos-project pull request #375
Opened 2023-03-06 13:02 UTC by sergiofenoll

Adds an extra "forever cache" that never gets invalidated to the stack. This is used for the concepts and concept schemes because they're static data and we want to prevent ever busting the cache (as some calls are pretty slow).

Related PRs:
- [ ] https://github.com/kanselarij-vlaanderen/cache-warmup-service/pull/11

Note: using `semtech/mu-cl-resource:feature-contstruct-based-fetches` lowered the request time considerable (from ~22s per batch to ~12s).

2023-03-07 13:34 UTC, tdn requested changes
Looks good. Just added a "request changes" to make sure the `cache-warmup-service` gets bumped before we merge this.

Also, out of curiosity because I honestly don't know: if not here, where is the `forever-cache` configured to be persistent forever? An environment variable? If so, how is it distinguished from the regular `cache` config?

2023-03-07 13:34 UTC, tdn commented on docker-compose.yml
> +    image: kanselarij/cache-warmup-service:feature-KAS-3797-slow-government-domain-requests
Note for when merging: bump kanselarij/cache-warmup-service first and add the correct version here

2023-03-07 13:39 UTC, sergiofenoll commented
> Looks good. Just added a "request changes" to make sure the `cache-warmup-service` gets bumped before we merge this.
> 
> Also, out of curiosity because I honestly don't know: if not here, where is the `forever-cache` configured to be persistent forever? An environment variable? If so, how is it distinguished from the regular `cache` config?

`mu-cl-resources` has an env variable for where to send cache clears to. In our stack [it's set to the (regular) cache](https://github.com/kanselarij-vlaanderen/app-kaleidos/pull/375/files#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3R140). By not changing that env variable the "forever cache" will never receive cache clears and won't be cleared.

2023-03-07 13:46 UTC, ValenberghsSven commented
Pretty sure we need some more config for jenkins to work with the cache. I'll take a look

2023-03-07 14:33 UTC, ValenberghsSven commented
From what I can tell we are also loading some other things into the forever cache, but dispatcher does not know about it yet
Talking about these 4
```
const STATIC_TYPES = [
  'publication-statuses',
  'publication-modes',
  'urgency-levels',
  'regulation-types',
];
```

2023-03-07 14:44 UTC, ValenberghsSven commented
Do we want to send other things to the `forever-cache`?  Could be follow-up ticket.
like themes, subcase-types, maybe others.

2023-03-07 15:11 UTC, ValenberghsSven commented
Are the allowed groups correct for admin? on "secretarie" the forever cache loads fast. on Admin, the government fields all miss the cache, still needing a very long load time.

2023-03-07 15:23 UTC, ValenberghsSven commented
also, no longer need custom builds. There is a frontend branch running https://github.com/kanselarij-vlaanderen/frontend-kaleidos/pull/1676

2023-03-07 15:30 UTC, ValenberghsSven commented
> Are the allowed groups correct for admin? on "secretarie" the forever cache loads fast. on Admin, the government fields all miss the cache the very first time, still needing a very long load time. No cache clears are incoming, so that works as expected.

Besides this weird behavior it seems to work nicely. tests on PR have started well (9 run without fail (including flaky agenda-notice.spec).

2023-03-07 15:32 UTC, sergiofenoll commented
> Are the allowed groups correct for admin? on "secretarie" the forever cache loads fast. on Admin, the government fields all miss the cache, still needing a very long load time.

I'll look into it. are all the first concept calls uncached, or which one specifically did you notice? IIRC the first call after logging in will always be uncached due to how the allowed groups are set on a request. So if you're noticing it on the first call it may be due to that?

2023-03-08 13:52 UTC, ValenberghsSven approved these changes

2023-03-08 13:52 UTC, merged