KAS-3978
kanselarij-vlaanderen/kaleidos-project pull request #404
Opened 2023-06-29 13:14 UTC by SchrodingersCat00

2023-07-04 10:00 UTC, ValenberghsSven requested changes
you need a `.graph` file with a `.ttl` file or your data is going to get inserted directly into the application graph `http://mu.semte.ch/application`.
This data needs to be in the public graph?

2023-08-10 11:47 UTC, ValenberghsSven commented
This will most likely need minor frontend changes so don't merge yet

2023-09-06 11:03 UTC, tdn approved these changes

2023-09-06 11:22 UTC, ValenberghsSven approved these changes

2023-09-06 11:23 UTC, merged