KAS-4683: Cabinet submissions
kanselarij-vlaanderen/kaleidos-project pull request #478
Opened 2024-06-03 10:41 UTC by sergiofenoll

https://kanselarij.atlassian.net/browse/KAS-4683

Adds the necessary types and config to enable cabinets to submit data to Kaleidos.

:warning: This will be hard to test without the frontend part as well.

Related PRs/services:

- [ ] https://github.com/kanselarij-vlaanderen/agenda-submission-service/pull/5
- [ ] https://github.com/kanselarij-vlaanderen/docx-conversion-service/pull/5
- [ ] https://github.com/kanselarij-vlaanderen/draft-file-service

2024-06-18 08:45 UTC, tdn requested changes
Some minimal changes/cleanup

2024-06-18 08:45 UTC, tdn commented on config/new-authorization/config.lisp
> +  ("subm:VoorloopigBestand" -> _))
`subm:VoorloopigBestand` -> `subm:VoorlopigBestand`

2024-06-18 08:45 UTC, tdn commented on config/resources/submissions-domain.lisp
> +                (:title               :string ,(s-prefix "dct:title"))
just as a remark: this is set to make a new `decisionmakingflow`

2024-06-18 08:45 UTC, tdn commented on config/resources/submissions-domain.lisp
> +                (:subcase-name        :string ,(s-prefix "ext:procedurestapNaam"))
subcase-name is not necessary

2024-06-18 08:45 UTC, tdn commented on config/migrations/20240604133010-submission-status.ttl
> +    skos:prefLabel "Ingediend" .
@ValenberghsSven suggests to add `schema:position` here

2024-06-18 08:45 UTC, tdn commented on config/resources/submissions-domain.lisp
> +                                      :as "status")
add comment: this is the submissions status (concept-scheme `thConceptScheme:ebfe253c-0537-11ee-bb35-ee395168dcf7`)

2024-06-18 08:45 UTC, tdn commented on docker-compose.yml
> +      FILE_RESOURCE_BASE: "http://themis.vlaanderen.be/id/bestand/"
change to http://themis.vlaanderen.be/id/voorlopig-bestand/

2024-07-16 14:48 UTC, ValenberghsSven approved these changes
tested

2024-07-16 14:58 UTC, merged