KAS-4890: Uitgestelde punten heragenderen met indieningen
kanselarij-vlaanderen/kaleidos-project pull request #504
Opened 2024-12-06 10:50 UTC by sergiofenoll

https://kanselarij.atlassian.net/browse/KAS-4890

Related PRs:

2024-12-06 11:43 UTC, sergiofenoll commented
This branches off from ACC, but I accidentally set the base branch of the PR to DEV.

2024-12-10 10:36 UTC, ValenberghsSven requested changes

2024-12-10 10:36 UTC, ValenberghsSven commented on config/migrations/20241205120355-postponed-item-submitted-status.ttl
> +    schema:position 7 ;
should be 8.
7 was used for "Aanpassing aangevraagd"

2024-12-11 16:20 UTC, ValenberghsSven commented on config/migrations/20241205120355-postponed-item-submitted-status.ttl
> +    schema:position 7 ;
fixed it

2024-12-20 16:08 UTC, ValenberghsSven commented
Changed base to DEV, no more rushing this

2025-01-07 11:34 UTC, tdn approved these changes

2025-01-07 15:48 UTC, ValenberghsSven approved these changes
updated the migration date, tagged the service

2025-01-07 15:48 UTC, merged