Kas 1420 beslissing behandeling agendapunt
kanselarij-vlaanderen/kaleidos-project pull request #94
Opened 2020-07-09 05:28 UTC by woutersf

### Model refactor decisions
⚠️  Deze PR kan niet zonder de PR's op frontend / yggdrasil / project / agenda approve service en de nieuwe migratieservice

✅  Cypress testen ok.
👓 controle wel required!

2020-07-17 18:51 UTC, ValenberghsSven requested changes
Hoe zit dat met newsletterinfo ?
Volgens de migraties (nr 3) verschuift die naar treatment.
Maar de resources zijn daar voor de rest niet geupdate voor.

Als het verplaatst is, hoe werkt dat dan naar frontend toe?
Momenteel heeft een procedurestap maar 1 nieuwsbrief. maar er kunnen wel meerdere treatments zijn.
Meerdere treatments, dus ook meerdere nieuwsbrieven voor 1 procedurestap?

In de frontend maken we normaal direct nieuwsbrieven aan bij aanmaken procedurestap.
Nu zal er dus geen nieuwsbrief gemaakt kunnen worden vooraleer er een beslissing is gemaakt ?
Daar zullen de mensen van kort bestek niet blij mee zijn denk ik.

2020-07-17 18:51 UTC, ValenberghsSven commented on config/resources/besluit-domain.lisp
> +                                :as "newsletter-info")
Ik ben wat in de war met dit.
Uit de migrations kan ik afleiden dat de nieuwsbrief van procedurestap weggaat en dat je dit aan treatment gaat hangen.
Maar op procedurestap hangt nog steeds een newsletter-info.
Ook is de relatie niet juist ? moet dit niet ```prov:generated``` zijn ?  of ```prov:generates``` ??
in migratie 3 zit een insert van ```?behandeling prov:generated ?nli .```
in migratie 7 zit een insert van ```?treatment prov:generates ?nli .```

ext:hasNewsletterInfo wordt nergens anders gebruikt dan deze 1 keer in resources ..

2020-07-17 18:51 UTC, ValenberghsSven commented on config/resources/document-domain.lisp
> +            ;                             :as "agenda-item-treatment")
beslissen of dit erin moet of niet. In commentaar laten staan is geen correcte optie.
query op prod op deze relatie geeft 300k + resultaten op beslissingen

2020-07-17 18:51 UTC, ValenberghsSven commented on config/resources/besluit-domain.lisp
> +              )
beslissen of dit erin moet of niet. In commentaar laten staan is geen correcte optie.

2020-07-17 18:51 UTC, ValenberghsSven commented on config/resources/besluit-domain.lisp
> +                                :inverse t
Dit is een beetje raar.
Op basis van het oslo model kan ik zien hoe je hieraan komt.
Een verslag IS een stuk dat een Beslissingsactiviteit beschrijft, de activiteit komt omdat een behandeling een Beslissingsactiviteit heeft.
Aangezien we geen verslag of Beslissingsactiviteit hebben, leggen jullie rechtstreeks een link tussen dossier:Serie en besluit:BehandelingVanAgendapunt

Maar is het niet logischer dat we hier opteren voor de relatie besluitvorming:genereertVerslag?
https://test.data.vlaanderen.be/ns/besluitvorming#genereertVerslag
(die lijn ligt after de paarse nieuwsbriefinfo)

![image](https://user-images.githubusercontent.com/22245223/87799779-ecda7c00-c84d-11ea-9ff1-a9b0160bb8f9.png)

2020-07-17 18:51 UTC, ValenberghsSven commented on config/resources/besluit-domain.lisp
> +;              )
wat met dit ?
Die inverse hier neerschijven is optioneel denk ik?

2020-07-17 18:51 UTC, ValenberghsSven commented on config/authorization/config.ex
>        "http://schema.org/Comment",
ext:BeslissingsResultaatCode is niet in de config te vinden.
Dit is vermoedelijk ook een public resource dus moet die zowel en all resources als unconfidential resources

2020-07-17 18:51 UTC, ValenberghsSven commented on config/resources/besluit-domain.lisp
> +  :on-path "agenda-item-treatments")
has one subcase nog leggen 
``` besluitvorming:vindtPlaatsTijdens ```
Zie comment in jira ticket

2020-07-17 18:51 UTC, ValenberghsSven commented on config/resources/dossier-domain.lisp
> -                                      :as "decisions")
hasmany treatments ?
relatie vertrekt volgens oslo vanuit treatment dus inverse hier.
```
besluitvorming:vindtPlaatsTijdens
```

2020-07-17 18:51 UTC, ValenberghsSven commented on config/resources/besluit-domain.lisp
> -                (:richtext      :string   ,(s-prefix "ext:htmlInhoud"))) ;; NOTE: Inherited from Document
Deze property richtext (ext:htmlInhoud) is zomaar verwijderd, in de migraties is hier niets van terug te vinden
Zoeken op deze op prod geeft wel data, vooral dit:
```
"              <!---->

&nbsp;

<!-- components -->
<!---->"
```
Op eerste zicht lijkt dat dit veld niet gebruikt werd, maar dit zou dus ergens bij in DELETE moeten, wss in migratie 2 ?

2020-07-17 18:51 UTC, ValenberghsSven commented on config/resources/document-domain.lisp
> +                                        )
:as "agenda-item-treatment"))

ligt meer in lijn met andere plaatsen waar we de beide haakjes op 1 lijn zetten
+ afhankelijk van andere comment, inverse hier en geneertVerslag gebruiken ?

2020-07-29 08:29 UTC, MikiDi commented on config/migrations/20200616142826-decision-result-code.sparql
> +            skos:prefLabel "Afkeuring"@nl .
Misschien moeten we voor consistentie de keuze maken tussen voltooid deelwoord of zelfstandig naamwoord voor alle labels :-) (voorkeur voor VD)

2020-07-29 09:27 UTC, MikiDi commented on config/resources/besluit-domain.lisp
> +              )
Omdat de mu-cl-resources configuratie momenteel onze meest accurate documentatie is over huidig model / huidige data, laat ik 'm er toch graag in. Dit predicaat is in-data veel aanwezig (en waardevolle data), en zal in de toekomst terug opgepikt worden. Behoeft wel nog een comment. Geen uitgecommente dingen zonder verdere uitleg, helemaal akkoord.

2020-07-29 09:38 UTC, MikiDi commented on config/resources/besluit-domain.lisp
> +                                :inverse t
> Aangezien we geen verslag of Beslissingsactiviteit hebben, leggen jullie rechtstreeks een link tussen dossier:Serie en besluit:BehandelingVanAgendapunt
Toch wel, we hebben een verslag, zijnde de beslissingsfiche. Dat is ook waarmee we hier linken. Wat het verwarrend maakt, is dat we hier (om story haalbaar te houden), nog niet helemaal conformeren met het model. Wij koppelen hier met een `dossier:Serie` ("document") ipv een `dossier:Stuk` ("document-versie"), omdat dat tot nu toe ook zo was. Behoeft idd meer uitleg en een todo onder vorm van een comment.
> is het niet logischer dat we hier opteren voor de relatie besluitvorming:genereertVerslag?
Gezien we gekozen hebben voor groeperen onder `besluit:BehandelingVanAgendapunt`, klinkt dat idd logischer

2020-07-29 12:11 UTC, MikiDi commented on config/resources/besluit-domain.lisp
> +                                :as "newsletter-info")
> Uit de migrations kan ik afleiden dat de nieuwsbrief van procedurestap weggaat en dat je dit aan treatment gaat hangen.

Check. Op die manier maken we ook de weg vrij voor Nieuwsbriefinfo bij zowel gewone agendapunten als mededelingen.

> Maar op procedurestap hangt nog steeds een newsletter-info

Als dat zo is, moet die verplaatst worden. Ik kijk het na.
> ext:hasNewsletterInfo wordt nergens anders gebruikt dan deze 1 keer in resources ..

Goed gezien. Ik kan me vaag herinneren dat we hier wat over en weer gegaan zijn. De conclusie was "we gaan voor [prov:generated](https://www.w3.org/TR/2013/REC-prov-o-20130430/#generated)". Gelijk te trekken

2020-07-29 12:15 UTC, MikiDi commented on config/resources/besluit-domain.lisp
> +;              )
Voor de inverse ("Geef me eens de code 'goedgekeurd' en alle behandelingen met die status") hebben we momenteel inderdaad geen use-case. Mag weg van mij (ook te checken in ember-data model).

2020-07-29 12:26 UTC, MikiDi commented on config/resources/document-domain.lisp
> +                                        )
Check. Cfr comment hierboven ivm verslag (beslissingsfiche). `besluitvorming:beschrijft` vervangen door `besluitvorming:genereertVerslag`.

2020-07-29 12:28 UTC, MikiDi commented on config/resources/document-domain.lisp
> +            ;                             :as "agenda-item-treatment")
De inverse mag wat mij betreft weg voor nu. Voor de andere (zie hierboven), graag comment houden met verduidelijking.

2020-07-29 12:33 UTC, MikiDi commented on config/resources/besluit-domain.lisp
> +  :on-path "agenda-item-treatments")
Klopt. Omdat we `Beslissingsactiviteit` samen nemen onder `BehandelingVanAgendapunt`, moeten we ook de eigenschappen/relaties van de Beslissingsactiviteit onderbrengen bij de `BehandelingVanAgendapunt`.

2020-07-31 10:07 UTC, woutersf commented on config/resources/document-domain.lisp
> +                                        )
Ik heb hiervoor een migratie geschreven en de occurences aangepast.

2020-08-04 11:08 UTC, woutersf commented on config/resources/besluit-domain.lisp
> +                                :inverse t
https://github.com/kanselarij-vlaanderen/behandeling-van-agendapunt-migration/commit/c0774e03578594cd363cec1b16b704cf54a62452

2020-08-05 09:48 UTC, MikiDi commented on config/resources/dossier-domain.lisp
> +                                  :inverse t
Een activiteit (agendering) `vindt plaats tijdens` een procedurestap, en niet omgekeerd. Inverse moet hier weg.

2020-09-01 08:09 UTC, merged