KAS-1758 added publicSince to document-domain-lisp
kanselarij-vlaanderen/kaleidos-project pull request #96
Opened 2020-07-27 08:57 UTC by brechtPhilips

# KAS-1758: Added publicSince to document-domain-lisp

## Changed:
- `document-domain-lisp`

2020-07-31 09:46 UTC, woutersf approved these changes

2020-08-17 14:39 UTC, ValenberghsSven requested changes

2020-08-17 14:39 UTC, ValenberghsSven commented on config/resources/document-domain.lisp
> +
geen new line hier

2020-08-17 14:39 UTC, ValenberghsSven commented
gelinkt aan https://github.com/kanselarij-vlaanderen/kaleidos-frontend/pull/456
Samen mergen indien beide ok.

2020-08-17 20:12 UTC, MikiDi commented on config/resources/document-domain.lisp
> +
mm :thinking: `:boolean`?

2020-08-20 09:44 UTC, BenjaminDendas approved these changes

2020-08-20 09:52 UTC, BenjaminDendas commented on config/resources/document-domain.lisp
> +
@brechtPhilips dit vraagt nog een aanpassing denk ik, `public-since` lijkt me inderdaad geen boolean..

2020-08-20 09:53 UTC, BenjaminDendas requested changes

2020-08-20 09:53 UTC, BenjaminDendas commented on config/resources/document-domain.lisp
> +                (:public-since          :boolean  ,(s-prefix "ext:publiekSinds")))
Dit gaat waarschijnlijk een `DateTime` type nodig hebben

2020-08-20 13:43 UTC, BenjaminDendas approved these changes
Fixed all issues

2020-08-20 13:43 UTC, merged